name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:

  test:
    environment: CI
    defaults:
      run:
        working-directory: ${{ github.workspace }}
    strategy:
      matrix:
        go-version: [1.19.x, 1.22.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Setup Credentials
      shell: bash
      env:
        GSHEET_GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GSHEET_GOOGLE_APPLICATION_CREDENTIALS }}
      run: |
        echo "$GSHEET_GOOGLE_APPLICATION_CREDENTIALS" > creds.json

    - name: Test
      shell: bash
      run: |
        export GOOGLE_APPLICATION_CREDENTIALS=$(python -c 'import os, sys; print(os.path.realpath("creds.json"))')
        go test -v ./...
